apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: "ph-ee-demo"
  labels:
    app: ph-ee-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-demo
  template:
    metadata:
      labels:
        app: ph-ee-demo
      annotations: {}
    spec:
      containers:
        - name: ph-ee-demo
          image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/demo2:latest"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
---
apiVersion: "v1"
kind: Service
metadata:
  labels:
    app: ph-ee-demo
  name: ph-ee-demo
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ph-ee-demo
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: ph-ee-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "demo2.sandbox.fynarfin.io"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ph-ee-demo
                port:
                  number: 80
  tls:
    - hosts:
        - "*.sandbox.fynarfin.io"
      secretName: "sandbox-secret"
